exclude: "^docs/source/conf.py$"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-case-conflict
    -   id: check-vcs-permalinks
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [ '--allow-missing-credentials']  # Avoid failure on CI
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck
        name: Shellcheck
        args: ["-f", "gcc"]  # output filename:linenum:colnum (clickable)
-   repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
    hooks:
      - id: hadolint
        name: Hadolint (Dockerfile checker)
# Actual Python Linter
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.146
    hooks:
      - id: ruff
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        name: Mypy (Python type-checker)
        additional_dependencies: [types-PyYAML==6.0.12.2]
